### ISSUE TITLE
Provide instructions how to host your own binaries server

### ISSUE THREAD

**Issue by DamianReeves** [chawyehsu/moonup#96]
I'm stuck behind a corporate firewall that won't allow access to https://moonup.csu.moe/v2 . It would be great if instructions on how to run your own binaries server could be provided.

It would also be great if you had a version of the URL that was directly off of github pages without the .moe domain.

**Comment by chawyehsu** [comment]
Here's dist server API spec with final upstream endpoints:

```yaml
HOST: https://moonup.csu.moe/v2
API:

/index.json
- https://chawyehsu.github.io/moonbit-binaries/v2/index.json

/channel-<channel>.json
- https://chawyehsu.github.io/moonbit-binaries/v2/channel-<channel>.json

/<channel>/<spec>/<arch-triplet>.json
- https://chawyehsu.github.io/moonbit-binaries/v2/<channel>/<spec>/<arch-triplet>.json

/download/<tag>/<filename> # `latest` channel
- https://github.com/chawyehsu/moonbit-binaries/releases/download/v<tag>/<filename>

/download/<tag>/<filename> # `nightly` channel
- https://github.com/chawyehsu/moonbit-dist-nightly/releases/download/nightly-<tag>/<filename>
```

You may write a simple http server to proxy upstream endpoints and provide the same APIs, run your server, and alter the dist server with the `MOONUP_DIST_SERVER` env var.

<details>

<summary>Example server by AI</summary>

Just POC, it may requires extra tweaks to work.

```py
from flask import Flask, jsonify, send_file
import requests
import os
from urllib.parse import quote

app = Flask(__name__)

BASE_URL = "https://chawyehsu.github.io/moonbit-binaries/v2"
GITHUB_RELEASE_URL = "https://github.com/chawyehsu/moonbit-binaries/releases/download"
GITHUB_NIGHTLY_URL = "https://github.com/chawyehsu/moonbit-dist-nightly/releases/download"

@app.route('/index.json')
def get_index():
    response = requests.get(f"{BASE_URL}/index.json")
    return response.json()

@app.route('/channel-<channel>.json')
def get_channel(channel):
    response = requests.get(f"{BASE_URL}/channel-{channel}.json")
    return response.json()

@app.route('/<channel>/<spec>/<arch_triplet>.json')
def get_arch_spec(channel, spec, arch_triplet):
    response = requests.get(f"{BASE_URL}/{channel}/{spec}/{arch_triplet}.json")
    return response.json()

@app.route('/download/<tag>/<path:filename>')
def download_file(tag, filename):
    # Determine if it's a nightly build based on the tag
    if tag.startswith('nightly-'):
        url = f"{GITHUB_NIGHTLY_URL}/{tag}/{quote(filename)}"
    else:
        url = f"{GITHUB_RELEASE_URL}/v{tag}/{quote(filename)}"
    
    response = requests.get(url)
    return response.content, response.status_code, response.headers.items()

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5000, debug=True)
```

You may add extra features such as cache mechanism per your needs.

</details>

There are multiple final endpoints from different github repos (there could be more as new channels introducing), it's not ideal to request directly to GitHub pages, therefore the middleware was introduced.
